project_name: seihon

builds:
  - binary: seihon
    env:
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: seihon
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

brews:
  - github:
      owner: ldez
      name: homebrew-tap
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/ldez/seihon
    description: Simple tool to publish multi-arch images on the Docker Hub
    test: |
      system "#{bin}/seihon version"

#release:
#  disable: true